-- Carvoo Database Schema - Clean Reset Version
-- This script drops all existing tables and recreates them from scratch

-- ============================================
-- DROP EXISTING TABLES (in reverse dependency order)
-- ============================================

-- Drop tables that depend on other tables first
DROP TABLE IF EXISTS public.product_views CASCADE;
DROP TABLE IF EXISTS public.wishlists CASCADE;
DROP TABLE IF EXISTS public.cart_items CASCADE;
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.models CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.brands CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- ============================================
-- CREATE TABLES
-- ============================================

-- 1. Create Profiles Table (extends auth.users)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    avatar_url TEXT,
    phone TEXT,
    address TEXT,
    shop_name TEXT,
    role TEXT CHECK (role IN ('admin', 'seller', 'buyer')) DEFAULT 'buyer',
    is_approved BOOLEAN DEFAULT TRUE, -- Default true for buyers, set to false for sellers by trigger
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Brands Table
CREATE TABLE public.brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Models Table
CREATE TABLE public.models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    brand_id BIGINT REFERENCES public.brands(id) ON DELETE CASCADE,
    vehicle_type TEXT, -- e.g., "SUV", "Sedan", "Hatchback"
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Categories Table
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    icon_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Create Products Table
CREATE TABLE public.products (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price DECIMAL(12,2) NOT NULL,
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    seller_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    brand_id BIGINT REFERENCES public.brands(id),
    model_id BIGINT REFERENCES public.models(id),
    category_id BIGINT REFERENCES public.categories(id),
    images TEXT[] DEFAULT '{}',
    status TEXT CHECK (status IN ('pending', 'approved', 'rejected', 'out_of_stock')) DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Create Orders Table
CREATE TABLE public.orders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    buyer_id UUID REFERENCES public.profiles(id) NOT NULL,
    total_amount DECIMAL(12,2) NOT NULL,
    status TEXT CHECK (status IN ('pending', 'accepted', 'processing', 'shipped', 'delivered', 'cancelled')) DEFAULT 'pending',
    payment_method TEXT DEFAULT 'COD',
    delivery_address TEXT NOT NULL,
    contact_number TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Create Order Items Table
CREATE TABLE public.order_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
    product_id UUID REFERENCES public.products(id) NOT NULL,
    quantity INTEGER NOT NULL,
    price_at_purchase DECIMAL(12,2) NOT NULL
);

-- Categories Policies
CREATE POLICY "Categories are viewable by everyone" ON public.categories FOR SELECT USING (true);

-- Brands Policies
CREATE POLICY "Brands are viewable by everyone" ON public.brands FOR SELECT USING (true);

-- Models Policies
CREATE POLICY "Models are viewable by everyone" ON public.models FOR SELECT USING (true);

-- Order Items Policies
CREATE POLICY "Buyers can view their own order items" ON public.order_items FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.orders o WHERE o.id = public.order_items.order_id AND o.buyer_id = auth.uid())
);
CREATE POLICY "Buyers can insert their own order items" ON public.order_items FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.orders o WHERE o.id = public.order_items.order_id AND o.buyer_id = auth.uid())
);
CREATE POLICY "Sellers can view items for their products" ON public.order_items FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.products p WHERE p.id = public.order_items.product_id AND p.seller_id = auth.uid())
);

-- 8. Create Reviews Table
CREATE TABLE public.reviews (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id UUID REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Create Cart Items Table
CREATE TABLE public.cart_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    product_id UUID REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, product_id)
);

-- 10. Create Wishlists Table
CREATE TABLE public.wishlists (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    product_id UUID REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, product_id)
);

-- 11. Create Product Views Analytics Table
CREATE TABLE public.product_views (
    product_id UUID REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    viewed_at DATE DEFAULT CURRENT_DATE NOT NULL,
    view_count INTEGER DEFAULT 1 NOT NULL,
    PRIMARY KEY (product_id, viewed_at)
);

-- 12. Create Messages Table
CREATE TABLE public.messages (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    sender_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    receiver_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    content TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================
-- ENABLE ROW LEVEL SECURITY
-- ============================================

-- ============================================
-- HELPER FUNCTIONS (Non-Recursive)
-- ============================================

-- Check if user is an admin via JWT
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Check if user is the buyer of an order
CREATE OR REPLACE FUNCTION public.is_order_buyer(check_order_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.orders
    WHERE id = check_order_id AND buyer_id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Check if user is the seller of any item in an order
CREATE OR REPLACE FUNCTION public.is_order_seller(check_order_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.order_items oi
    JOIN public.products p ON oi.product_id = p.id
    WHERE oi.order_id = check_order_id AND p.seller_id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.models ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- ============================================
-- ROW LEVEL SECURITY POLICIES
-- ============================================

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admins can manage all profiles" ON public.profiles FOR ALL USING (public.is_admin());

-- Product Policies
CREATE POLICY "Approved products are viewable by everyone" ON public.products FOR SELECT USING (status = 'approved');
CREATE POLICY "Sellers can view their own products" ON public.products FOR SELECT USING (auth.uid() = seller_id);
CREATE POLICY "Sellers can insert their own products" ON public.products FOR INSERT WITH CHECK (auth.uid() = seller_id);
CREATE POLICY "Sellers can update their own products" ON public.products FOR UPDATE USING (auth.uid() = seller_id);
CREATE POLICY "Sellers can delete their own products" ON public.products FOR DELETE USING (auth.uid() = seller_id);
CREATE POLICY "Admins can manage all products" ON public.products FOR ALL USING (public.is_admin());

-- Order Policies
CREATE POLICY "Orders access policy" ON public.orders FOR SELECT USING (
    public.is_admin() OR 
    auth.uid() = buyer_id OR 
    public.is_order_seller(id)
);

CREATE POLICY "Buyers can create their own orders" ON public.orders FOR INSERT WITH CHECK (auth.uid() = buyer_id);
CREATE POLICY "Admins can update orders" ON public.orders FOR UPDATE USING (public.is_admin());

-- Order Items Policies
CREATE POLICY "Order items access policy" ON public.order_items FOR SELECT USING (
    public.is_admin() OR 
    public.is_order_buyer(order_id) OR
    EXISTS (SELECT 1 FROM public.products WHERE id = product_id AND seller_id = auth.uid())
);

CREATE POLICY "Admins can manage order items" ON public.order_items FOR ALL USING (public.is_admin());

-- Review Policies
CREATE POLICY "Reviews are viewable by everyone" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Authenticated users can create reviews" ON public.reviews FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Cart Policies
CREATE POLICY "Users can view their own cart" ON public.cart_items FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own cart" ON public.cart_items FOR ALL USING (auth.uid() = user_id);

-- Wishlist Policies
CREATE POLICY "Users can view their own wishlist" ON public.wishlists FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own wishlist" ON public.wishlists FOR ALL USING (auth.uid() = user_id);

-- Product Views Policies
CREATE POLICY "Product views are viewable by everyone" ON public.product_views FOR SELECT USING (true);
CREATE POLICY "Authenticated users can increment views" ON public.product_views FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can update views" ON public.product_views FOR UPDATE USING (auth.role() = 'authenticated');

-- Message Policies
CREATE POLICY "Users can view their own messages" ON public.messages FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = receiver_id);
CREATE POLICY "Users can send messages" ON public.messages FOR INSERT WITH CHECK (auth.uid() = sender_id);
CREATE POLICY "Users can update their own messages" ON public.messages FOR UPDATE USING (auth.uid() = sender_id);
CREATE POLICY "Admins can manage all messages" ON public.messages FOR ALL USING (public.is_admin());

-- Reviews Policies (if not already viewable)
CREATE POLICY "Admins can manage all reviews" ON public.reviews FOR ALL USING (public.is_admin());

-- ============================================
-- PERFORMANCE INDEXES
-- ============================================

-- Products Table Indexes
CREATE INDEX idx_products_status ON public.products(status);
CREATE INDEX idx_products_category ON public.products(category_id) WHERE category_id IS NOT NULL;
CREATE INDEX idx_products_seller ON public.products(seller_id);
CREATE INDEX idx_products_created ON public.products(created_at DESC);
CREATE INDEX idx_products_price ON public.products(price);
CREATE INDEX idx_products_brand ON public.products(brand_id) WHERE brand_id IS NOT NULL;
CREATE INDEX idx_products_model ON public.products(model_id) WHERE model_id IS NOT NULL;

-- Orders Table Indexes
CREATE INDEX idx_orders_buyer ON public.orders(buyer_id);
CREATE INDEX idx_orders_status ON public.orders(status);
CREATE INDEX idx_orders_created ON public.orders(created_at DESC);

-- Order Items Table Indexes
CREATE INDEX idx_order_items_order ON public.order_items(order_id);
CREATE INDEX idx_order_items_product ON public.order_items(product_id);

-- Cart Items Table Indexes
CREATE INDEX idx_cart_items_user ON public.cart_items(user_id);
CREATE INDEX idx_cart_items_product ON public.cart_items(product_id);

-- Wishlists Table Indexes
CREATE INDEX idx_wishlists_user ON public.wishlists(user_id);
CREATE INDEX idx_wishlists_product ON public.wishlists(product_id);

-- Reviews Table Indexes
CREATE INDEX idx_reviews_product ON public.reviews(product_id);
CREATE INDEX idx_reviews_user ON public.reviews(user_id);

-- Models Table Indexes
-- ============================================
-- SEED DATA
-- ============================================

-- Initial Categories
INSERT INTO public.categories (name, slug, icon_name) VALUES 
('Engine & Parts', 'engine-parts', 'settings'),
('Transmission', 'transmission', 'refresh-cw'),
('Brake System', 'brake-system', 'disc'),
('Suspension', 'suspension', 'activity'),
('Electrical', 'electrical', 'zap'),
('Body & Exterior', 'body-exterior', 'layout'),
('Interior & Accessories', 'interior-accessories', 'armchair')
ON CONFLICT (slug) DO NOTHING;

-- Initial Brands
INSERT INTO public.brands (name) VALUES 
('Toyota'), ('Honda'), ('Ford'), ('BMW'), ('Mercedes-Benz'), ('Audi'), ('Hyundai'), ('Nissan')
ON CONFLICT (name) DO NOTHING;
